# Generated by Django 5.0.4 on 2024-04-28 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth_app_user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request_details',
            name='number',
            field=models.BigIntegerField(default=0),
        ),
    ]
