# Generated by Django 5.0.4 on 2024-04-28 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth_app_user', '0003_alter_request_details_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='request_details',
            name='status',
            field=models.CharField(default='Pending', max_length=25),
        ),
    ]
